# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /z/richox-compression/zling

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /z/richox-compression/zling

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /z/richox-compression/zling/CMakeFiles /z/richox-compression/zling/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /z/richox-compression/zling/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ./zling_demo

# Build rule for target.
./zling_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ./zling_demo
.PHONY : ./zling_demo

# fast build rule for target.
./zling_demo/fast:
	$(MAKE) -f CMakeFiles/./zling_demo.dir/build.make CMakeFiles/./zling_demo.dir/build
.PHONY : ./zling_demo/fast

#=============================================================================
# Target rules for targets named zling

# Build rule for target.
zling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zling
.PHONY : zling

# fast build rule for target.
zling/fast:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/build
.PHONY : zling/fast

sample/zling.o: sample/zling.cpp.o
.PHONY : sample/zling.o

# target to build an object file
sample/zling.cpp.o:
	$(MAKE) -f CMakeFiles/./zling_demo.dir/build.make CMakeFiles/./zling_demo.dir/sample/zling.cpp.o
.PHONY : sample/zling.cpp.o

sample/zling.i: sample/zling.cpp.i
.PHONY : sample/zling.i

# target to preprocess a source file
sample/zling.cpp.i:
	$(MAKE) -f CMakeFiles/./zling_demo.dir/build.make CMakeFiles/./zling_demo.dir/sample/zling.cpp.i
.PHONY : sample/zling.cpp.i

sample/zling.s: sample/zling.cpp.s
.PHONY : sample/zling.s

# target to generate assembly for a file
sample/zling.cpp.s:
	$(MAKE) -f CMakeFiles/./zling_demo.dir/build.make CMakeFiles/./zling_demo.dir/sample/zling.cpp.s
.PHONY : sample/zling.cpp.s

src/libzling.o: src/libzling.cpp.o
.PHONY : src/libzling.o

# target to build an object file
src/libzling.cpp.o:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling.cpp.o
.PHONY : src/libzling.cpp.o

src/libzling.i: src/libzling.cpp.i
.PHONY : src/libzling.i

# target to preprocess a source file
src/libzling.cpp.i:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling.cpp.i
.PHONY : src/libzling.cpp.i

src/libzling.s: src/libzling.cpp.s
.PHONY : src/libzling.s

# target to generate assembly for a file
src/libzling.cpp.s:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling.cpp.s
.PHONY : src/libzling.cpp.s

src/libzling_huffman.o: src/libzling_huffman.cpp.o
.PHONY : src/libzling_huffman.o

# target to build an object file
src/libzling_huffman.cpp.o:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_huffman.cpp.o
.PHONY : src/libzling_huffman.cpp.o

src/libzling_huffman.i: src/libzling_huffman.cpp.i
.PHONY : src/libzling_huffman.i

# target to preprocess a source file
src/libzling_huffman.cpp.i:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_huffman.cpp.i
.PHONY : src/libzling_huffman.cpp.i

src/libzling_huffman.s: src/libzling_huffman.cpp.s
.PHONY : src/libzling_huffman.s

# target to generate assembly for a file
src/libzling_huffman.cpp.s:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_huffman.cpp.s
.PHONY : src/libzling_huffman.cpp.s

src/libzling_lz.o: src/libzling_lz.cpp.o
.PHONY : src/libzling_lz.o

# target to build an object file
src/libzling_lz.cpp.o:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_lz.cpp.o
.PHONY : src/libzling_lz.cpp.o

src/libzling_lz.i: src/libzling_lz.cpp.i
.PHONY : src/libzling_lz.i

# target to preprocess a source file
src/libzling_lz.cpp.i:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_lz.cpp.i
.PHONY : src/libzling_lz.cpp.i

src/libzling_lz.s: src/libzling_lz.cpp.s
.PHONY : src/libzling_lz.s

# target to generate assembly for a file
src/libzling_lz.cpp.s:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_lz.cpp.s
.PHONY : src/libzling_lz.cpp.s

src/libzling_utils.o: src/libzling_utils.cpp.o
.PHONY : src/libzling_utils.o

# target to build an object file
src/libzling_utils.cpp.o:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_utils.cpp.o
.PHONY : src/libzling_utils.cpp.o

src/libzling_utils.i: src/libzling_utils.cpp.i
.PHONY : src/libzling_utils.i

# target to preprocess a source file
src/libzling_utils.cpp.i:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_utils.cpp.i
.PHONY : src/libzling_utils.cpp.i

src/libzling_utils.s: src/libzling_utils.cpp.s
.PHONY : src/libzling_utils.s

# target to generate assembly for a file
src/libzling_utils.cpp.s:
	$(MAKE) -f CMakeFiles/zling.dir/build.make CMakeFiles/zling.dir/src/libzling_utils.cpp.s
.PHONY : src/libzling_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ./zling_demo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zling"
	@echo "... sample/zling.o"
	@echo "... sample/zling.i"
	@echo "... sample/zling.s"
	@echo "... src/libzling.o"
	@echo "... src/libzling.i"
	@echo "... src/libzling.s"
	@echo "... src/libzling_huffman.o"
	@echo "... src/libzling_huffman.i"
	@echo "... src/libzling_huffman.s"
	@echo "... src/libzling_lz.o"
	@echo "... src/libzling_lz.i"
	@echo "... src/libzling_lz.s"
	@echo "... src/libzling_utils.o"
	@echo "... src/libzling_utils.i"
	@echo "... src/libzling_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

